name: LifeSteal
version: '2'
api-version: 1.20
main: org.fliff.lifeSteal.LifeSteal
authors: [ Fluffy ]
commands:
  resethearts:
    description: Resets the hearts of a player.
    usage: /resethearts <player>
    permission: lifesteal.reset
  withdrawheart:
    description: Withdraws hearts into items.
    usage: /withdrawheart <amount>
    permission: lifesteal.withdraw
  lifestealplugin:
    description: Manage LifeSteal Plugin
    usage: /lifestealplugin reload
    permission: lifesteal.reload
